<?php

namespace App\Enums;

enum VerificationType: string
{
    // National Documents
    case NIN = 'NIN';
    case BVN = 'BVN';
    case PASSPORT = 'PASSPORT';
    case DRIVER_LICENSE = 'DRIVER_LICENSE';
    case VOTER_CARD = 'VOTER_CARD';
    case NATIONAL_ID_CARD = 'NATIONAL_ID_CARD';
    case RESIDENCE_PERMIT = 'RESIDENCE_PERMIT';
    case TAX_IDENTIFICATION_NUMBER = 'TAX_IDENTIFICATION_NUMBER';

    // International Documents
    case INTERNATIONAL_PASSPORT = 'INTERNATIONAL_PASSPORT';
    case FOREIGN_NATIONAL_ID_CARD = 'FOREIGN_NATIONAL_ID_CARD';
    case PERMANENT_RESIDENT_CARD = 'PERMANENT_RESIDENT_CARD';
    case WORK_PERMIT = 'WORK_PERMIT';
    case STUDENT_ID_CARD = 'STUDENT_ID_CARD';
    case REFUGEE_ID_CARD = 'REFUGEE_ID_CARD';

    // Identity Cards
    case ID_CARD = 'ID_CARD';
    case STATE_ID_CARD = 'STATE_ID_CARD';
    case CITY_ID_CARD = 'CITY_ID_CARD';

    // Health Insurance Cards
    case HEALTH_INSURANCE_CARD = 'HEALTH_INSURANCE_CARD';
    case NATIONAL_HEALTH_INSURANCE_CARD = 'NATIONAL_HEALTH_INSURANCE_CARD';

    // Social Security Cards
    case SOCIAL_SECURITY_CARD = 'SOCIAL_SECURITY_CARD';
    case NATIONAL_SOCIAL_SECURITY_CARD = 'NATIONAL_SOCIAL_SECURITY_CARD';

    // Phone and Address Verifications
    case PHONE_NUMBER = 'PHONE_NUMBER';
    case ADDRESS = 'ADDRESS';

    // Biometric Verifications
    case FACIAL_RECOGNITION = 'FACIAL_RECOGNITION';
    case FINGERPRINT_RECOGNITION = 'FINGERPRINT_RECOGNITION';
    case IRIS_RECOGNITION = 'IRIS_RECOGNITION';

    // Other Verifications
    case EMAIL_VERIFICATION = 'EMAIL_VERIFICATION';
    case BANK_ACCOUNT_VERIFICATION = 'BANK_ACCOUNT_VERIFICATION';
    case CREDIT_CARD_VERIFICATION = 'CREDIT_CARD_VERIFICATION';
}